"""Create workflows table

Revision ID: 5dcbdcec8321
Revises: 7d7dac88be54
Create Date: 2026-07-03 13:21:04.883284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcbdcec8321'
down_revision: Union[str, Sequence[str], None] = '7d7dac88be54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('stage', sa.Enum('PRD', 'SYSTEM_DESIGN', 'SPRINT_PLAN', 'COMPLETED', name='workflowstage'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'WAITING_FOR_REVIEW', 'FAILED', 'COMPLETED', name='workflowstatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    # ### end Alembic commands ###
